### ISSUE TITLE
'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by David56038** [123woscc/tianmao_shop_spider#2]
Traceback (most recent call last):
  File "tianmao.py", line 136, in <module>
    print(rs.get())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by Diane513** [comment]
同，请问找到解决方法了吗
